version: "3"
services:
       quizwhiz:
           container_name: my-node-app-con
           image: my-node-app
           restart: always
           build: .
           ports:
             - "3001:3001"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'
